name: Auto Concept Car Daily

on:
  schedule:
    - cron: "0 5 * * *"     # 05:00 UTC ~ 07:00 Paris (été); 06:00 Paris (hiver)
  workflow_dispatch: {}      # Active le bouton "Run workflow"

permissions:
  contents: write

concurrency:
  group: auto-concept-car
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TZ: Europe/Paris

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "openai>=1.51.0"

      - name: Generate concept car (images + article + index)
        run: |
          python scripts/auto_concept_car.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: daily concept car $(date +'%Y-%m-%d %H:%M %Z')"
            git push
          else
            echo "No changes to commit."
          fi
