name: Auto Concept Car Daily

on:
  schedule:
    - cron: "0 4 * * *"   # 04:00 UTC ~ 06:00 CET/CEST (selon période)
    - cron: "0 5 * * *"   # sécurité pour bascules d'heure
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TZ: Europe/Paris
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate concept car (images + article + index)
        run: |
          python scripts/auto_concept_car.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: daily concept car $(date +'%Y-%m-%d %H:%M %Z')"
            git push
          else
            echo "No changes to commit."
          fi
