name: Auto Concept Car Daily

on:
  schedule:
    - cron: "0 5 * * *"   # Tous les jours à 5h UTC (7h heure de Paris)
  workflow_dispatch:       # Permet aussi de lancer manuellement

permissions:
  contents: write   # 👈 donne le droit de push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    - name: Generate concept car (images + article + index)
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |

	python scripts/auto_concept_car.py

   - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add articles/ images/ index.html
        git commit -m "Ajout recette du $(date +'%Y-%m-%d')" || echo "Rien à commit"
        git push
